// Random Number Guessing Game:
// Develop a program that generates a random number between 1 and 100.
//  Allow the user to guess the number and provide feedback on whether the guess is too high, too low, or correct.

function compareRandomNumbers(userGuess){
    const randomNumber = Math.floor(Math.random() * 100) + 1;
        console.log('Random Number generated by program is', randomNumber);
    
    if(userGuess > randomNumber)
    {
        console.log( "Your guessed number is higher, try again");
    }
    
    else if (userGuess < randomNumber)
    {
        console.log( "Your guessed number is lower, try again");
    }
    else {
        console.log( "Your guessed number is mine too. Correct!");
    
    }
    }
    console.log(compareRandomNumbers(6));